Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 38, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 38, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 40, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 40, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    products = shopify.Product.find()
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 385, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 522, in _find_every
    path = cls._collection_path(prefix_options, query_options)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 613, in _collection_path
    'prefix': cls._prefix(prefix_options),
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 737, in _prefix
    path = re.sub('/$', '', cls.prefix_source)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 311, in get_prefix_source
    return urllib.parse.urlsplit(cls.site)[2]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 181, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    products = shopify.Product.find()
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 385, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 522, in _find_every
    path = cls._collection_path(prefix_options, query_options)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 613, in _collection_path
    'prefix': cls._prefix(prefix_options),
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 737, in _prefix
    path = re.sub('/$', '', cls.prefix_source)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 311, in get_prefix_source
    return urllib.parse.urlsplit(cls.site)[2]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 181, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    products = shopify.Product.find()
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 385, in find
    return cls._find_every(from_=from_, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 522, in _find_every
    path = cls._collection_path(prefix_options, query_options)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 613, in _collection_path
    'prefix': cls._prefix(prefix_options),
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 737, in _prefix
    path = re.sub('/$', '', cls.prefix_source)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 311, in get_prefix_source
    return urllib.parse.urlsplit(cls.site)[2]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 181, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if line_items[i]["variant_id"] == product.variants[i].id:
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if line_items[i]["variant_id"] == product.variants[i].id:
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if line_items[i]["variant_id"] == product.variants[i].id:
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if line_items[i]["variant_id"] == product.variants[i].id:
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if line_items[i]["variant_id"] == product.variants[i].id:
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id: and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id: and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id: and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 53
    if (line_items[i]["variant_id"] == product.variants[i].id and product.variants[i].inventory_management == "shopify" and product.variants[i].inventory_quantity < 10):
     ^
IndentationError: expected an indented block
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 39, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Not Found: /twilio_call/chocolate
Not Found: /twilio_call/chocolate
Not Found: /twilio_call/
Not Found: /twilio_call/chocolate/
Not Found: /twilio_call/chocolate/
Internal Server Error: /twilio_call/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 130, in get_response
    % (callback.__module__, view_name))
ValueError: The view shopify_app.views.twilio_call didn't return an HttpResponse object. It returned None instead.
Forbidden (CSRF cookie not set.): /twilio_call/chocolate/
Forbidden (CSRF cookie not set.): /twilio_call/chocolate/
Forbidden (CSRF cookie not set.): /twilio_call/chocolate/
Internal Server Error: /twilio_call/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'Say' object has no attribute 'get'
Not Found: /twilio/chocolate
Not Found: /twilio/chocolate/
Not Found: /articles/chocolate/
Not Found: /articles/chocolate/
Not Found: /articles/chocolate/
Internal Server Error: /articles/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
TypeError: twilio_call() got an unexpected keyword argument 'year'
Internal Server Error: /articles/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'Say' object has no attribute 'get'
Internal Server Error: /articles/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 130, in get_response
    % (callback.__module__, view_name))
ValueError: The view shopify_app.views.twilio_call didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /articles/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 65
    return HttpResponse(resp.say("Hello, your product %s has less than 10 items left in inventory." % product_name)))
                                                                                                                    ^
SyntaxError: invalid syntax
Not Found: /twilio_call/chocolate/
Internal Server Error: /twilio_call/chocolate/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options', None) is not None:
AttributeError: 'str' object has no attribute 'get'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 40, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 40, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 26, in home
    make_call(product["title"])
TypeError: 'Product' object has no attribute '__getitem__'
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 26, in home
    make_call(product.get("title"))
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 1083, in _instance_get
    return self.klass.connection.get(url, self.klass.headers)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/connection.py", line 329, in get
    return self.format.decode(self._open('GET', path, headers=headers).body)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify/base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/pyactiveresource/connection.py", line 268, in _open
    six.iteritems(request.headers)])
TypeError: sequence item 1: expected string, NoneType found
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 26, in home
    make_call(product.title)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/making_call.py", line 11, in make_call
    url=call_url)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/calls.py", line 147, in create
    return self.create_instance(kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 365, in create_instance
    data=transform_params(body))
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 200, in request
    resp = make_twilio_request(method, uri, auth=self.auth, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 164, in make_twilio_request
    uri=resp.url, msg=message, code=code)
TwilioRestException: 
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST https://api.twilio.com/2010-04-01/Accounts/AC076d19dc21badaf44ec008f4aa8ca73e/Calls.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUrl is not a valid URL: http://4f5bf394.ngrok.com/twilio_call/Updated Product Title/[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21402[0m


Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 27, in home
    make_call(product.title)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/making_call.py", line 11, in make_call
    url=call_url)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/calls.py", line 147, in create
    return self.create_instance(kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 365, in create_instance
    data=transform_params(body))
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 200, in request
    resp = make_twilio_request(method, uri, auth=self.auth, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 164, in make_twilio_request
    uri=resp.url, msg=message, code=code)
TwilioRestException: 
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST https://api.twilio.com/2010-04-01/Accounts/AC076d19dc21badaf44ec008f4aa8ca73e/Calls.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUrl is not a valid URL: http://4f5bf394.ngrok.com/twilio_call/Updated Product Title/[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21402[0m


Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 27, in home
    make_call(product.title)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/making_call.py", line 11, in make_call
    url=call_url)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/calls.py", line 147, in create
    return self.create_instance(kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 365, in create_instance
    data=transform_params(body))
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 200, in request
    resp = make_twilio_request(method, uri, auth=self.auth, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/twilio/rest/resources/base.py", line 164, in make_twilio_request
    uri=resp.url, msg=message, code=code)
TwilioRestException: 
[31m[49mHTTP Error[0m [37m[49mYour request was:[0m

[36m[49mPOST https://api.twilio.com/2010-04-01/Accounts/AC076d19dc21badaf44ec008f4aa8ca73e/Calls.json[0m

[37m[49mTwilio returned the following information:[0m

[34m[49mUrl is not a valid URL: http://4f5bf394.ngrok.com/twilio_call/Updated Product Title/[0m

[37m[49mMore information may be available here:[0m

[34m[49mhttps://www.twilio.com/docs/errors/21402[0m


Not Found: /twilio_call/Updated,Product,Title/
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 44, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 44, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 44, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 44, in webhook
    for product in products:
NameError: global name 'products' is not defined
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 43, in webhook
    with request.user.session:
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute 'session'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 48, in webhook
    line_items = json.loads(request.body)["line_items"]
KeyError: 'line_items'
Internal Server Error: /order_webhook/
Traceback (most recent call last):
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/lib/python2.7/site-packages/shopify_auth/decorators.py", line 44, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/nakulpathak/Documents/Projects/shopify-app/shopify_app/views.py", line 49, in webhook
    for i in range(0, len(line_items)):
NameError: global name 'line_items' is not defined
